######################################################################
# Automatically generated by qmake (2.01a) ven. avr. 12 19:17:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lgiac -lgmp

# Input
HEADERS += ContextTab.h GraphicalCore.h headcomment.h
SOURCES += ContextTab.cpp GraphicalCore.cpp main.cpp
